title: William Miller # your name (or website title) here
logo: "images/Professional Photo (2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is William Miller and I study Economics, Political Science, and History at the University of Oklahoma.
  I am proficient in Python and have experience applying data analysis methods to social science questions.
  <br>
  <a href= "https://politicaldataanalytics.com/">My Newsletter</a>
  <br>
  <br>
  <a href= "https://www.linkedin.com/in/williammiller6/">My LinkedIn</a>
  
  
theme: jekyll-theme-minimal

