title: William Miller # your name (or website title) here
logo: "images/Professional Photo (2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is William Miller and I study Political Science, Economics, and History at the University of Oklahoma.
  It is my goal to use data analytics to help drive the next generation of public policy.
  <br><br> 
  
theme: jekyll-theme-minimal

